### ISSUE TITLE
have system based tabs as a component for easy loading/interacting (mac/windows/linux)

### ISSUE THREAD

**Issue by hanbollar** [KittyCAD/documentation#27]
we should do something not toggle based but more tab based that makes better sense to the user like github's style with: https://docs.github.com/en/authentication/connecting-to-github-with-ssh/checking-for-existing-ssh-keys?platform=mac

it has tabs that auto change the content and autodetects what tab should be loaded --> obv we'll need to figure out a better visual setup since it's not that noticeable right of the bat visually, but would be a better setup than the drop downs for usability

_Originally posted by @hanbollar in https://github.com/KittyCAD/PetStore/issues/99#issuecomment-1343334378_

**Comment by jessfraz** [comment]
This is related and a better UX imo https://github.com/KittyCAD/website/issues/614 would be nice if we could reuse the same react component for both
