### ISSUE TITLE
tutorials section

### ISSUE THREAD

**Issue by hanbollar** [KittyCAD/documentation#33]
- [ ] recommendations on the tutorial homepage based on most recent added - and if they havent done any api calls yet, we make sure the beginner and adv onboarding tutorials are at the front
- [ ] remove automatic alphabetical ordering for the left side just for this page and allow for manually ordered and groupings with the two onboarding tutorials grouped in the onboarding section at the top
- [x] change titling for `onboarding` to `advanced onboarding` tutorial and `beginner tutorial` to `beginner onboarding` tutorial

**Comment by hanbollar** [comment]
the titling can be done by @jgomez720 , but i think @Irev-Dev you're needed for the first two parts

**Comment by Irev-Dev** [comment]
What if we always have the beginner and advanced tutorial at the top, than a some whitespace or maybe a small heading and then the rest of the tutorials ordered by date added (most recent at the top)?

I'm not sure content navigation should be dynamic, things moving around could be frustrating for users trying to find the same content again.

**Comment by hanbollar** [comment]
> What if we always have the beginner and advanced tutorial at the top, than a some whitespace or maybe a small heading and then the rest of the tutorials ordered by date added (most recent at the top)?
> 
> I'm not sure content navigation should be dynamic, things moving around could be frustrating for users trying to find the same content again.

hmmm - only reason im saying otherwise, is that once the alphabetization of the left-side is removed, the goal is for the left bar to have tutorials grouped by topic and in proper order - which means we can make sure theyre always at the top for easy grab from the side-bar (same thing for the rest of the tutorials) - and eventually we'll also have a search bar so it's easier to grab anyways
(adding more detail to that checklist item to add the goal note)

it becomes a bit redundant for devs and engineers who already did the onboarding to always see the onboarding on the main page when it's still easy to grab

maybe we could add it as part of the account checklist too tho? like if they havent generated an api key yet or called it from the command line, it recommends the tutorial as a task still to be completed?

**Comment by hanbollar** [comment]
old - main part of request no longer relevant, closing
